# -*- coding: utf-8 -*-
"""software eng exp1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GoXME0s0_uMFw8WKuKl3JD_ohHxR1Jms
"""

#weather modelling using the quadractic eqn
a=5
b=4
c=6
x=4.5
y=a * x * x + b * x + c
print('the value of y is ',y)